steps:
- checkout: self  # 👈 Ensures the repo content is pulled

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install databricks-cli --upgrade
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF
  displayName: 'Install and Authenticate Databricks CLI'

- script: |
    echo "Debug: listing repo files..."
    ls -R
  displayName: 'Debug: List Files in Workspace'

- script: |
    echo "Deploying all notebooks..."
    databricks workspace import_dir deltaliverepo /Shared/QA/deltaliverepo --overwrite
  displayName: 'Deploy Notebooks to QA Workspace'
