steps:
- checkout: self  # 👈 Ensures the repo content is pulled

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install databricks-cli --upgrade
    pip install databricks-sdk
    export DATABRICKS_HOST="$(DATABRICKS_HOST)"
    export DATABRICKS_TOKEN="$(DATABRICKS_TOKEN)"
    echo "Authentication complete"
  displayName: 'Authenticate Databricks CLI via Environment Variables'

- script: |
    echo "Debug: listing repo files..."
    ls -R
  displayName: 'Debug: List Files in Workspace'
- script: |
    echo "Showing root contents..."
    ls -la

    echo "Checking deltaliverepo folder..."
    ls -la deltaliverepo
  displayName: 'Debug: Check Folder Structure'
  continueOnError: true

- script: |
    echo "Deploying notebooks to QA..."
    databricks workspace import-dir --profile default --overwrite dlt-config-demo /Shared/QA/dlt-config-demo
    databricks workspace import-dir --profile default --overwrite dlt-scd-demo /Shared/QA/dlt-scd-demo
  displayName: 'Deploy Notebooks to QA Workspace'

