trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Databricks-Dev-Auth  # This variable group should contain DATABRICKS_HOST and DATABRICKS_TOKEN

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
    databricks --version
  displayName: 'Install Databricks CLI v2'

- script: |
    echo "Deploying notebooks to QA..."
    databricks workspace import-dir dlt-config-demo /Shared/QA/dlt-config-demo --overwrite
    databricks workspace import-dir dlt-scd-demo /Shared/QA/dlt-scd-demo --overwrite
  displayName: 'Deploy Notebooks to QA Workspace'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
