trigger:
- none  # or set to 'main' or 'develop' when you're ready

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Databricks-Dev-Auth

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install databricks-cli --upgrade
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF

    echo "Authenticated with Databricks!"
  displayName: 'Install and Authenticate Databricks CLI'
